openapi: 3.0.0

info:
  title: API Bank Caixa
  description: mock for api at Bank Caixa
  version: 1.0.0

paths:
  /api/authentication:
    post:
      tags:
        - Authentication
      summary: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Authentication_SiginupRequest'
      responses:
        '200':
          description: bea
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 200
                  token:
                    type: string
                    example: Bearer myToken
    put:
      tags:
        - Authentication
      summary: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Authentication_LoginRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 200
                  token:
                    type: string
                    example: Bearer myToken

components:
  schemas:
    Authentication_SiginupRequest:
      type: object
      properties:
        username:
          type: string
          required: true
        password:
          type: string
          required: true
        document:
          required: true
    Authentication_LoginRequest:
      type: object
      properties:
        clientId:
          type: string
          required: true
        clientSecret:
          type: string
          required: true
