openapi: 3.0.0

info:
  title: API Bank Caixa
  description: mock for api at Bank Caixa
  version: 1.0.0

paths:
  /api/authentication:
    post:
      tags:
        - Authentication
      summary: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Authentication_SiginupRequest'
      responses:
        '200':
          description: Authorization successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Authorization successful
    put:
      tags:
        - Authentication
      summary: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Authentication_LoginRequest'
      responses:
        '200':
          description: Authorization successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Authorization successful
    get:
      tags:
        - Authentication
      summary: authorize
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Authorization successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Authorization successful

components:
  securitySchemes:
    bearerAuth:    
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Authentication_SiginupRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        document:
          type: string
      required:
        - username
        - password
        - document
        
    Authentication_LoginRequest:
      type: object
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
      required:
        - clientId
        - clientSecret
